<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9344c467a487955893b3c2602f6fe3cf
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PagSeguro\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PagSeguro\\' => 
        array (
            0 => __DIR__ . '/..' . '/pagseguro/pagseguro-php-sdk/source',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9344c467a487955893b3c2602f6fe3cf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9344c467a487955893b3c2602f6fe3cf::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
